import { ArrowUpRight, BarChart3, Clock3, Eye, Globe2, MousePointerClick } from 'lucide-react';
import { db } from '@/lib/db';

export const dynamic = 'force-dynamic';

export default async function AnalyticsPage() {
  const posts = await db.post.findMany({ orderBy: { views: 'desc' }, take: 8 }); const total = posts.reduce((sum, post) => sum + post.views, 0); const bars = [28, 36, 32, 51, 48, 67, 58, 81, 73, 92, 78, 88];
  return <div className="content"><div className="page-heading"><div><div className="eyebrow">Performance intelligence</div><h1>访问分析</h1><p className="subtitle">用轻量数据看清哪些内容值得继续写，哪些入口需要优化。</p></div><button className="button ghost"><Clock3 size={15} /> 最近 30 天</button></div><div className="metric-grid"><Metric icon={<Eye size={17} />} label="总阅读" value={total.toLocaleString()} foot="较上周期 +18.4%" /><Metric icon={<MousePointerClick size={17} />} label="平均阅读时长" value="03:42" foot="较上周期 +12.1%" /><Metric icon={<Globe2 size={17} />} label="独立访客" value="2,184" foot="来自 21 个国家 / 地区" /><Metric icon={<BarChart3 size={17} />} label="回访率" value="42.8%" foot="内容粘性良好" /></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h2>阅读量走势</h2><p>模拟接入统计服务后的展示区</p></div><ArrowUpRight size={17} color="var(--muted)" /></div><div className="panel-body"><div className="chart">{bars.map((value, index) => <div className="chart-col" key={index}><div className="bar-track"><div className="bar" style={{ height: `${value}%` }} /></div><span>{index + 1}日</span></div>)}</div></div></section><section className="panel"><div className="panel-head"><div><h2>热门文章</h2><p>按累计阅读量排序</p></div><BarChart3 size={17} color="var(--muted)" /></div><div className="table-wrap"><table><thead><tr><th>文章</th><th>阅读</th></tr></thead><tbody>{posts.map((post) => <tr key={post.id}><td><span className="table-title">{post.title}</span><span className="table-sub">/{post.slug}</span></td><td>{post.views.toLocaleString()}</td></tr>)}</tbody></table></div></section></div><section className="panel" style={{ marginTop: 14 }}><div className="panel-head"><div><h2>下一步建议</h2><p>根据当前内容结构给出的运营提醒</p></div></div><div className="panel-body"><div className="quick-grid"><div className="quick-action"><strong>补充标签体系</strong><span>当前文章的标签覆盖偏少，补齐后会让归档页更好用。</span></div><div className="quick-action"><strong>优化文章摘要</strong><span>优先完善热门文章的摘要，有助于搜索结果点击。</span></div></div></div></section></div>;
}

function Metric({ icon, label, value, foot }: { icon: React.ReactNode; label: string; value: string; foot: string }) { return <div className="metric-card"><div className="metric-top"><span>{label}</span><span className="metric-icon">{icon}</span></div><div className="metric-value">{value}</div><div className="metric-foot positive">{foot}</div></div>; }
