'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { CheckSquare, ExternalLink, Filter, MoreHorizontal, Pencil, Search, Send, Trash2 } from 'lucide-react';
import { useRouter } from 'next/navigation';

type Post = { id: string; title: string; slug: string; category: string; status: string; views: number; featured: boolean; updatedAt: string; createdAt: string };

export default function PostList({ posts }: { posts: Post[] }) {
  const router = useRouter(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [selected, setSelected] = useState<string[]>([]); const [message, setMessage] = useState('');
  const visible = useMemo(() => posts.filter((post) => (filter === 'all' || post.status === filter) && (!query || `${post.title} ${post.slug} ${post.category}`.toLowerCase().includes(query.toLowerCase()))), [posts, filter, query]);
  const allVisible = visible.length > 0 && visible.every((post) => selected.includes(post.id));
  const toggleAll = () => setSelected(allVisible ? selected.filter((id) => !visible.some((post) => post.id === id)) : Array.from(new Set([...selected, ...visible.map((post) => post.id)])));
  const remove = async (id: string) => { if (!window.confirm('确定要删除这篇文章吗？')) return; const response = await fetch(`/api/posts/${id}`, { method: 'DELETE' }); if (!response.ok) { setMessage('删除失败，请稍后重试'); return; } router.refresh(); };
  const publish = async (id: string) => { setMessage('正在提交到 GitHub…'); const response = await fetch(`/api/posts/${id}/publish`, { method: 'POST' }); const body = await response.json().catch(() => ({})); if (!response.ok) { setMessage(body.detail || '发布失败，请检查 GitHub 配置'); return; } setMessage('发布成功，Pages workflow 已开始构建'); router.refresh(); };
  return <><div className="toolbar"><div className="toolbar-left"><div className="filter-tabs">{[['all', '全部'], ['published', '已发布'], ['draft', '草稿'], ['scheduled', '定时']].map(([value, label]) => <button key={value} className={`filter-tab ${filter === value ? 'active' : ''}`} onClick={() => setFilter(value)}>{label}</button>)}</div><div className="search"><input className="input" placeholder="搜索标题、Slug、分类" value={query} onChange={(event) => setQuery(event.target.value)} /></div></div><div className="toolbar-right"><button className="button small ghost"><Filter size={14} /> 更多筛选</button>{selected.length > 0 && <button className="button small">已选 {selected.length} 篇</button>}</div></div>{message && <div className="save-bar" style={{ marginBottom: 12 }}><span>{message}</span><button className="button small ghost" onClick={() => setMessage('')}>知道了</button></div>}<section className="panel"><div className="table-wrap"><table><thead><tr><th style={{ width: 44 }}><input className="checkbox" type="checkbox" checked={allVisible} onChange={toggleAll} aria-label="全选" /></th><th>文章</th><th>分类</th><th>状态</th><th>阅读</th><th>最后编辑</th><th style={{ width: 130 }}>操作</th></tr></thead><tbody>{visible.length ? visible.map((post) => <tr key={post.id}><td><input className="checkbox" type="checkbox" checked={selected.includes(post.id)} onChange={() => setSelected((current) => current.includes(post.id) ? current.filter((id) => id !== post.id) : [...current, post.id])} aria-label={`选择 ${post.title}`} /></td><td><Link className="table-title" href={`/posts/${post.id}`}>{post.title}</Link><span className="table-sub">/{post.slug}{post.featured ? ' · 精选' : ''}</span></td><td>{post.category}</td><td><span className={`status ${post.status}`}>{statusLabel(post.status)}</span></td><td>{post.views.toLocaleString()}</td><td>{new Intl.DateTimeFormat('zh-CN', { month: 'short', day: 'numeric' }).format(new Date(post.updatedAt))}</td><td><div className="row-actions"><Link className="icon-button" href={`/posts/${post.id}`} title="编辑"><Pencil size={14} /></Link>{post.status !== 'published' && <button className="icon-button" onClick={() => publish(post.id)} title="发布"><Send size={14} /></button>}<button className="icon-button" onClick={() => remove(post.id)} title="删除"><Trash2 size={14} /></button><button className="icon-button" title="更多"><MoreHorizontal size={14} /></button></div></td></tr>) : <tr><td colSpan={7}><div className="empty"><Search size={20} style={{ marginBottom: 8 }} /><div>没有匹配的文章</div></div></td></tr>}</tbody></table></div><div className="pagination"><span>显示 {visible.length} / {posts.length} 篇文章</span><span><CheckSquare size={13} style={{ verticalAlign: 'middle', marginRight: 5 }} />支持批量选择</span></div></section></>;
}

function statusLabel(value: string) { return ({ published: '已发布', draft: '草稿', scheduled: '定时发布' } as Record<string, string>)[value] || value; }
